#!/bin/sh

NEW_ROOT='/mnt/root'

PrintAndDie() {
	echo ""
	echo "/init failed: $*"
	echo ""
	echo "ERROR! Dropping to a shell so you can figure it out"
	exec /bin/busybox sh
	exit 0
}

IsFileExists() {
	if [ "$(ls -a -d $1 2> /dev/null)" = "" ]; then
		return 1
	fi
	return 0
}

# Mount the /proc and /sys filesystems.
mount -t proc none /proc
mount -t sysfs none /sys
# ------------------------------------------------------------------------------
# Do your stuff here.
#/bin/splash_scr /root/logo.bmp
# ------------------------------------------------------------------------------
# Mount rootfs
CMD_LINE=$(cat /proc/cmdline)
ROOT=$(echo "$CMD_LINE" | sed -r 's/(.*)root=([^ ]+)(.*)/\2/')
ROOT_FS_TYPE=$(echo "$CMD_LINE" | sed -r 's/(.*)rootfstype=([^ ]+)(.*)/\2/')

if ! IsFileExists "$NEW_ROOT"; then
	mkdir "$NEW_ROOT" || PrintAndDie "Failed to create: $NEW_ROOT"
fi

mount -t $ROOT_FS_TYPE $ROOT $NEW_ROOT || PrintAndDie "Failed to mount: $ROOT"

# Clean up
umount /proc
umount /sys

# Boot the real thing
exec switch_root $NEW_ROOT /sbin/init
