#!/bin/sh

GPIO_SYS_DIR='/sys/class/gpio/'
VD1_2=110
VD3_4=109
SPEAKER=111
PSU_SAVE=41
PSU_RESET=40

GPIOexport() {
    local pin_id=$1
    local pin_dir=$2
    local trig=$3
    local val=$4
    echo $pin_id > $GPIO_SYS_DIR/export
    echo $pin_dir > $GPIO_SYS_DIR/gpio${pin_id}/direction
    echo $trig > $GPIO_SYS_DIR/gpio${pin_id}/active_low
    echo $val > $GPIO_SYS_DIR/gpio${pin_id}/value
}

GPIOintExport() {
    local pin_id=$1
    echo $pin_id   > $GPIO_SYS_DIR/export
    echo "in"      > $GPIO_SYS_DIR/gpio${pin_id}/direction
    echo "falling" > $GPIO_SYS_DIR/gpio${pin_id}/edge
}

GPIOexport $VD1_2 out 0 0
GPIOexport $VD3_4 out 0 1
GPIOexport $SPEAKER out 0 1 

# Denis: Такой подход не работает, возникли проблемы на испытаниях.
#GPIOintExport $PSU_SAVE
#GPIOintExport $PSU_RESET
# Блокируем эти ножки.
GPIOexport $PSU_SAVE out 0 1
GPIOexport $PSU_RESET out 0 1
