#!/bin/sh

VIDEO_DEV='/dev/fb0'
VIDEO_MOD=$(cat /sys/class/graphics/fb0/mode | grep -Eo '([0-9]+)+x([0-9]+)') #1024x768'
DISPLAY=':0.0'
KILLPROC=''
REGIGRAF_DIR='/home/regigraf'
TSLIB_TSDEVICE='/dev/input/event0'

export DISPLAY
export TSLIB_TSDEVICE

if [ -f "$REGIGRAF_DIR/main" ]; then
	KILLPROC='main'
else
	KILLPROC='X'
fi

StartGUI() {
	if [ "$KILLPROC" = 'main' ]; then
		echo -n "Starting Regigraf: "
		cd "$REGIGRAF_DIR/" && ./main &
		return
	fi
	echo -n "Starting X server: "
	X $DISPLAY -screen $VIDEO_MOD -rgba rgb -mouse tslib,1,,device=$TSLIB_TSDEVICE -fb $VIDEO_DEV &
}

StartCmd() {
	StartGUI
	echo "OK"
}

StopCmd() {
	echo -n "Stopping GUI: "
	killall -9 $KILLPROC
	echo "OK"
}

case "$1" in
    start) StartCmd;;
    stop ) StopCmd;;
    restart|reload)
	StopCmd
	StartCmd
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
