#!/bin/sh
#
# Start the network....
#

BOARD_NAME=$(cat /proc/cpuinfo | grep -E 'Hardware(.*):(.*)' | sed -r 's/(.+): (.+)/\2/g') #'
HW_ADDR=$(cat /etc/hwaddr)

case "$1" in
  start)
 	echo "Starting network..."
	#/sbin/ifup -a
	/sbin/ifconfig lo up 127.0.0.1
	/sbin/ifconfig eth0 up hw ether $HW_ADDR
	# Hack
#	if [ "$BOARD_NAME" != 'MX53 Regiboard' ]; then
#		ethtool -s eth0 speed 10 duplex half
#	fi
	udhcpc -b -A 2147483647
	;;
  stop)
	echo -n "Stopping network..."
	/sbin/ifdown -a
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

